#+TITLE: NeoAmerica | Journal
#+AUTHOR: Vega Jerusalem
#+STARTUP: hidestars

<2020-12-31 Thu 04:30>
* DONE Start server
* DONE NEXT Hiccup page routed to index "Neo America"


** QUESTION Before it was just giving you raw text. This was necessary to get true html via hiccup
Ok so common-interceptors
- body-params/body-params http/html-body
...in the route :get (conj common-interceptors 'page)
* QUESTION
** Response Headers
*Content-Security-Policy* script-src and i assume css and the like? maybe not
*Strict-Transport-Security* max-age, subdomains
*Transfer-Encoding*
*X-Content-Type-Options: nosniff*
*X-Download-Options* set on DENY. What does this do?
*X-Frame-Options* html frames?
*X-Permitted-Cross-Domain-Policies* 
*X-XSS-Protection* Options?
* QUESTION I'm really interested in knowing how interceptors stack up. I see them grouped together in 'defs' then pages, etc are conj'd on. How does this work
 ANSWER - It really is that simple...it adds on to the interceptor chain 

* Interesting Read | https://heykieran.github.io/post/pedestal-buddy/
_Route_

=Roles=
*Roles are granted (or denied) HTTP verb access to individual uri’s which are represented in the Pedestal world as routes. A route may also be unprotected meaning that its uri is accessible to unauthenticated users (i.e. the public).*
*There are two ways to allow unprotected access to a resource*

*Do not use interceptors that manage or restrict access based on identity and permissions. (These interceptors are established for a route with the build-secured-route-vec-to function, which is dicussed in greater detail below).*
*Name the route using a value in the :alloc-public namespace (see note below on how the permissions lookup table is populated).*

* <2021-01-01 Fri>
** TODO Make a post and persist it to a map
** Should it be called a post, snippet, crumb, then you'll be able to categorize several small posts on a page to build your idea out.
** TODO Persist post to a database table
** TODO Validate it and stop your posts at either 500 words or a reasonable amount of characters
** DONE Pens should arrive. Start really writing



* <2021-01-05 Tue>
** TODO Start on NeoAmerica UI. Just the header 

* POSTGRES STUFF
Most \d commands support additional param of __schema__.name__ and accept wildcards like *.*

    \q: Quit/Exit
    \c __database__: Connect to a database
    \d __table__: Show table definition (columns, etc.) including triggers
    \d+ __table__: More detailed table definition including description and physical disk size
    \l: List databases
    \dy: List events
    \df: List functions
    \di: List indexes
    \dn: List schemas
    \dt *.*: List tables from all schemas (if *.* is omitted will only show SEARCH_PATH ones)
    \dT+: List all data types
    \dv: List views
    \dx: List all extensions installed
    \df+ __function__ : Show function SQL code.
    \x: Pretty-format query results instead of the not-so-useful ASCII tables
    \copy (SELECT * FROM __table_name__) TO 'file_path_and_name.csv' WITH CSV: Export a table as CSV
    \des+: List all foreign servers
    \dE[S+]: List all foreign tables
